spring.application.name=prediction
spring.datasource.url=jdbc:mysql://localhost:3306/project

spring.datasource.username=credit
spring.datasource.password=College@Project
#spring.h2.console.enabled=true

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto=update

#ogging.level.root = DEBUG

server.servlet.session.cookie.same-site = none;
